import javax.swing.*;

public class ForFamily extends JFrame {

    /**
     * Creates new form ForFamily
     */
    public ForFamily() {
        initComponents();
        this.setExtendedState(6);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar = new javax.swing.JToolBar();
        jKakaoBtn = new javax.swing.JButton();
        jStarrailBtn = new javax.swing.JButton();
        jDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar = new javax.swing.JMenuBar();
        jClientMnu = new javax.swing.JMenu();
        jClientInfoMnu = new javax.swing.JMenu();
        jProductMnu = new javax.swing.JMenu();
        jProductCodeMnu = new javax.swing.JMenuItem();
        jProductStockMnu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar.setRollover(true);

        jKakaoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kakao.jpg"))); // NOI18N
        jKakaoBtn.setFocusable(false);
        jKakaoBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jKakaoBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jKakaoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProductCodeMnuActionPerformed(evt);
            }
        });
        jToolBar.add(jKakaoBtn);

        jStarrailBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/star.jpg"))); // NOI18N
        jStarrailBtn.setFocusable(false);
        jStarrailBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jStarrailBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jStarrailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStarrailBtnActionPerformed(evt);
            }
        });
        jToolBar.add(jStarrailBtn);

        jDesktopPane.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 191, Short.MAX_VALUE)
        );

        jClientMnu.setText("고객관리");

        jClientInfoMnu.setText("고객정보");
        jClientMnu.add(jClientInfoMnu);

        jMenuBar.add(jClientMnu);

        jProductMnu.setText("물품관리");

        jProductCodeMnu.setText("물품코드");
        jProductCodeMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProductCodeMnuActionPerformed(evt);
            }
        });
        jProductMnu.add(jProductCodeMnu);

        jProductStockMnu.setText("입출고");
        jProductMnu.add(jProductStockMnu);

        jMenuBar.add(jProductMnu);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(jDesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jStarrailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStarrailBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jStarrailBtnActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        //종료 여부 확인
        int result = JOptionPane.showConfirmDialog(null, "Are you sure to exit?", "Confirm Exit",   

                                                 JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (result == JOptionPane.YES_OPTION) {

            this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

            this.dispose();

        } else {

            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);

        }
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        LoginDlg frm = new LoginDlg(this, true);
        frm.setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    private void jProductCodeMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProductCodeMnuActionPerformed
        ProductCodeFrm obj = new ProductCodeFrm();

        this.jDesktopPane.add(obj);

        obj.setVisible(true);
    }//GEN-LAST:event_jProductCodeMnuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForFamily.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForFamily.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForFamily.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForFamily.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForFamily().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jClientInfoMnu;
    private javax.swing.JMenu jClientMnu;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JButton jKakaoBtn;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jProductCodeMnu;
    private javax.swing.JMenu jProductMnu;
    private javax.swing.JMenuItem jProductStockMnu;
    private javax.swing.JButton jStarrailBtn;
    private javax.swing.JToolBar jToolBar;
    // End of variables declaration//GEN-END:variables
}
