/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import javax.swing.*;
/**
 *
 * @author gusal
 */
public class ScoreMgr extends JFrame {

    /**
     * Creates new form ScoreMgr
     */
    public ScoreMgr() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jModelPnl = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jNameTxt = new javax.swing.JTextField();
        jKorTxt = new javax.swing.JTextField();
        jEngTxt = new javax.swing.JTextField();
        jMatTxt = new javax.swing.JTextField();
        jAvgTxt = new javax.swing.JTextField();
        jControlPnl = new javax.swing.JPanel();
        jInsertBtn = new javax.swing.JButton();
        jDeleteBtn = new javax.swing.JButton();
        jDataRead = new javax.swing.JButton();
        jUpdateBtn = new javax.swing.JButton();
        jSearchBtn = new javax.swing.JButton();
        jDataWrite = new javax.swing.JButton();
        jResultPnl = new javax.swing.JPanel();
        jNavigationPnl = new javax.swing.JPanel();
        jFirstBtn = new javax.swing.JButton();
        jPrevBtn = new javax.swing.JButton();
        jNextBtn = new javax.swing.JButton();
        jLastBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jModelPnl.setBackground(new java.awt.Color(255, 153, 153));
        jModelPnl.setLayout(new java.awt.GridLayout(2, 0));

        jLabel2.setText("이름");
        jModelPnl.add(jLabel2);

        jLabel1.setText("국어");
        jModelPnl.add(jLabel1);

        jLabel3.setText("영어");
        jModelPnl.add(jLabel3);

        jLabel4.setText("수학");
        jModelPnl.add(jLabel4);

        jLabel5.setText("평균");
        jModelPnl.add(jLabel5);

        jNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNameTxtActionPerformed(evt);
            }
        });
        jModelPnl.add(jNameTxt);

        jKorTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKorTxtActionPerformed(evt);
            }
        });
        jModelPnl.add(jKorTxt);

        jEngTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEngTxtActionPerformed(evt);
            }
        });
        jModelPnl.add(jEngTxt);

        jMatTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMatTxtActionPerformed(evt);
            }
        });
        jModelPnl.add(jMatTxt);

        jAvgTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAvgTxtActionPerformed(evt);
            }
        });
        jModelPnl.add(jAvgTxt);

        jControlPnl.setBackground(new java.awt.Color(255, 204, 153));
        jControlPnl.setLayout(new java.awt.GridLayout(2, 0));

        jInsertBtn.setText("추가하기");
        jInsertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInsertBtnActionPerformed(evt);
            }
        });
        jControlPnl.add(jInsertBtn);

        jDeleteBtn.setText("삭제하기");
        jDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteBtnActionPerformed(evt);
            }
        });
        jControlPnl.add(jDeleteBtn);

        jDataRead.setText("파일읽기");
        jDataRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDataReadActionPerformed(evt);
            }
        });
        jControlPnl.add(jDataRead);

        jUpdateBtn.setText("변경하기");
        jUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateBtnActionPerformed(evt);
            }
        });
        jControlPnl.add(jUpdateBtn);

        jSearchBtn.setText("조회하기");
        jSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchBtnActionPerformed(evt);
            }
        });
        jControlPnl.add(jSearchBtn);

        jDataWrite.setText("파일쓰기");
        jDataWrite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDataWriteActionPerformed(evt);
            }
        });
        jControlPnl.add(jDataWrite);

        jResultPnl.setBackground(new java.awt.Color(255, 255, 102));
        jResultPnl.setLayout(new java.awt.GridLayout(1, 0));

        jNavigationPnl.setBackground(new java.awt.Color(153, 255, 153));
        jNavigationPnl.setLayout(new java.awt.GridLayout(1, 0));

        jFirstBtn.setText("<<");
        jFirstBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFirstBtnActionPerformed(evt);
            }
        });
        jNavigationPnl.add(jFirstBtn);

        jPrevBtn.setText("<");
        jPrevBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrevBtnActionPerformed(evt);
            }
        });
        jNavigationPnl.add(jPrevBtn);

        jNextBtn.setText(">");
        jNextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNextBtnActionPerformed(evt);
            }
        });
        jNavigationPnl.add(jNextBtn);

        jLastBtn.setText(">>");
        jLastBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLastBtnActionPerformed(evt);
            }
        });
        jNavigationPnl.add(jLastBtn);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jModelPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jControlPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jResultPnl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jNavigationPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jModelPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jControlPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jResultPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jNavigationPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNameTxtActionPerformed
        
    }//GEN-LAST:event_jNameTxtActionPerformed

    private void jKorTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKorTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jKorTxtActionPerformed

    private void jEngTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEngTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEngTxtActionPerformed

    private void jMatTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMatTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMatTxtActionPerformed

    private void jAvgTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAvgTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAvgTxtActionPerformed
    ArrayList<StudentVO> SearchList = new ArrayList<StudentVO>();
    ArrayList<StudentVO> totalList = new ArrayList<StudentVO>(); // totalList라는 이름의 Vector 리스트 사용
    ArrayList<StudentVO> showList=totalList;
    StudentVO clieckedStudentVO;
    
 
    
    
    private void showList(){ //showList 함수 생성
        this.jResultPnl.removeAll(); //처음부터 보여주기위해 함수 실행되면 계속해서 결과패널 초기화
        int from = currentPage * countPerPage; 
        int to = (currentPage+1) * countPerPage;
        if (to>=showList.size())
            to = showList.size();
        for (int i = from ; i<to; i++){ //showList 사이즈만큼 반복
            StudentVO studentVO = showList.get(i);  //쇼리스트의 i번째 값을 가져와서 studentVO에 넣음
            JButton obj = new SButton(studentVO); //넣어둔 studentVO값을 매개변수로 SButton obj 객체 생성
            obj.addActionListener(new java.awt.event.ActionListener() { //obj의 액션리스너 함수 사용(내부)
                @Override//오버라이드
                public void actionPerformed(ActionEvent e) { //내부함수 actionPerformed 오버라이드
                    SButton sButton = (SButton)e.getSource(); 
                    //getSource : 이벤트가 발생한 컴포넌트(버튼, 텍스트상자) 반환
                    //따라서 sButton은 이벤트 컴포넌트 반환 객체        
                    clieckedStudentVO = sButton.getStudentVO(); 
                    //SButton 클래스로 만든 객체 sButton의 studentVO객체를 clieckedStudentVO에 넣음
                    jNameTxt.setText(clieckedStudentVO.getName());
                    //jNameTxt를 setText 내부 함수로 내용 변경 (내용 : clickedStudentVO의 getName으로 가져와 해당 내용으로 setText) 이하 동일 
                    jKorTxt.setText("" + clieckedStudentVO.getKor());
                    jEngTxt.setText("" + clieckedStudentVO.getEng());
                    jMatTxt.setText("" + clieckedStudentVO.getMat());
                    
        }});
            this.jResultPnl.add(obj); //생성한 obj 객체를 결과 패널에 등록
        }
        this.pack(); // 화면갱신
        clieckedStudentVO = null;
    }
    
    private void jInsertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsertBtnActionPerformed
        StudentVO studentVO = new StudentVO( // studentVO 객체 생성
            this.jNameTxt.getText() // 그 객체안에 getText(내장함수)로 값을 입력받아 jNameTxt에 넣음
                +" "+this.jKorTxt.getText() //" "로 한번 띄우고 위와 같이 jKorTxt에 넣음
                +" "+this.jEngTxt.getText() //위와 같음 
                +" "+this.jMatTxt.getText() //위와 같음
        );
        totalList.add(studentVO);
        showTotalList();
//        currentPage = 0;
//        showList = totalList;
//        showList();
//        JButton obj = new SButton(studentVO); //위에서 만든 studentVO를 매개변수로 받아 obj 객체를 만든다 
//        //SButton은 JButton을 상속 받아 현재 이름과 평균을 출력하며 버튼을 출력하게 만들어진 클래스다.
//        this.jResultPnl.add(obj);//jResultPnl에 obj 객체 추가
        this.pack();//화면재설정
    }//GEN-LAST:event_jInsertBtnActionPerformed

    private void jDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteBtnActionPerformed
        if (clieckedStudentVO == null) // 클릭한 객체가 이미 빈 상태라면
            return; //아무 행동도 하지 않고 리턴
        this.totalList.remove(clieckedStudentVO);
        currentPage = 0;
//        showList = totalList;
//        showList();
//        this.pack();
            showTotalList();
    }//GEN-LAST:event_jDeleteBtnActionPerformed

    private void jDataReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDataReadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDataReadActionPerformed

    private void jUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateBtnActionPerformed
        if (clieckedStudentVO == null){
            JOptionPane aa=new JOptionPane();
            aa.showMessageDialog(null, "변경 학생 미지정");
            return; //아무 행동도 하지 않고 리턴
        } // 클릭한 객체가 이미 빈 상태라면
        clieckedStudentVO.setName(this.jNameTxt.getText());
        clieckedStudentVO.setKor(Integer.parseInt(this.jKorTxt.getText()));
        clieckedStudentVO.setEng(Integer.parseInt(this.jEngTxt.getText()));
        clieckedStudentVO.setMat(Integer.parseInt(this.jMatTxt.getText()));
        currentPage = 0;
        showTotalList();
    }//GEN-LAST:event_jUpdateBtnActionPerformed

    private void jSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchBtnActionPerformed
        StudentVO cmpObj = new StudentVO( //StudentVO 속성의 cmpObj 객체 생성
            this.jNameTxt.getText() 
                +" "+this.jKorTxt.getText()
                +" "+this.jEngTxt.getText()
                +" "+this.jMatTxt.getText()         
        );        
        SearchList.clear(); // 벡터 초기화 
        for (StudentVO studentVO : totalList){ //totalList값을 StudentVO속성을 가진 studentVO에 순서대로 넣음
            if(studentVO.compareTo(cmpObj)) //만약 studentVO값이 compareTo 메서드로 확인했을때
                                            // 일치하는 문자가 있다면
                SearchList.add(studentVO); //서치리스트 어레이리스트에 studentVO 값을 추가
        }
//        showList = SearchList; //쇼리스트에 서치리스트 값을 넣음
//        showList(); //쇼리스트 함수 사용
//        this.pack(); //화면 갱신
            showTotalList();
    }//GEN-LAST:event_jSearchBtnActionPerformed

    private void jDataWriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDataWriteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDataWriteActionPerformed

    int currentPage = 0; //페이지 초기화
    
    private void showTotalList(){
        currentPage = 0;
        showList = totalList;
        showList();
    }
    
    private void jFirstBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFirstBtnActionPerformed
        currentPage = 0;
        showList();
    }//GEN-LAST:event_jFirstBtnActionPerformed

    private void jPrevBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPrevBtnActionPerformed
        currentPage--;
        if(currentPage < 0)
            currentPage = 0;
        showList();
    }//GEN-LAST:event_jPrevBtnActionPerformed

    int countPerPage = 3;
    private void jNextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNextBtnActionPerformed
        currentPage++;
        if(showList.size() / countPerPage < countPerPage)
            currentPage = 0;
        showList();
    }//GEN-LAST:event_jNextBtnActionPerformed

    private void jLastBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLastBtnActionPerformed
        currentPage = showList.size() / countPerPage;
        showList();
    }//GEN-LAST:event_jLastBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoreMgr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoreMgr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoreMgr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoreMgr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScoreMgr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAvgTxt;
    private javax.swing.JPanel jControlPnl;
    private javax.swing.JButton jDataRead;
    private javax.swing.JButton jDataWrite;
    private javax.swing.JButton jDeleteBtn;
    private javax.swing.JTextField jEngTxt;
    private javax.swing.JButton jFirstBtn;
    private javax.swing.JButton jInsertBtn;
    private javax.swing.JTextField jKorTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jLastBtn;
    private javax.swing.JTextField jMatTxt;
    private javax.swing.JPanel jModelPnl;
    private javax.swing.JTextField jNameTxt;
    private javax.swing.JPanel jNavigationPnl;
    private javax.swing.JButton jNextBtn;
    private javax.swing.JButton jPrevBtn;
    private javax.swing.JPanel jResultPnl;
    private javax.swing.JButton jSearchBtn;
    private javax.swing.JButton jUpdateBtn;
    // End of variables declaration//GEN-END:variables
}
