
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import javax.swing.*;
import java.io.*;
import java.util.*;


public class ScoreMgr extends JFrame {

    /**
     * Creates new form ScoreMgr
     */
    public ScoreMgr() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jName = new javax.swing.JLabel();
        jKor = new javax.swing.JLabel();
        jEng = new javax.swing.JLabel();
        jMat = new javax.swing.JLabel();
        jAvg = new javax.swing.JLabel();
        jNameTxt = new javax.swing.JTextField();
        jKorTxt = new javax.swing.JTextField();
        jEngTxt = new javax.swing.JTextField();
        jMatTxt = new javax.swing.JTextField();
        jAvgTxt = new javax.swing.JTextField();
        jControlPnl = new javax.swing.JPanel();
        jInsertBtn = new javax.swing.JButton();
        jDeleteBtn = new javax.swing.JButton();
        jDataReadBtn = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jDescendingBtn = new javax.swing.JButton();
        jUpdateBtn = new javax.swing.JButton();
        jSearchBtn = new javax.swing.JButton();
        jDataWriteBtn = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jAscendingBtn = new javax.swing.JButton();
        jResultPnl = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jFirstBtn = new javax.swing.JButton();
        jPrevBtn = new javax.swing.JButton();
        jNextBtn = new javax.swing.JButton();
        jLastBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        jName.setText("이름");
        jPanel1.add(jName);

        jKor.setText("국어");
        jPanel1.add(jKor);

        jEng.setText("영어");
        jPanel1.add(jEng);

        jMat.setText("수학");
        jPanel1.add(jMat);

        jAvg.setText("평균");
        jPanel1.add(jAvg);

        jNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNameTxtActionPerformed(evt);
            }
        });
        jPanel1.add(jNameTxt);

        jKorTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKorTxtActionPerformed(evt);
            }
        });
        jPanel1.add(jKorTxt);

        jEngTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEngTxtActionPerformed(evt);
            }
        });
        jPanel1.add(jEngTxt);

        jMatTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMatTxtActionPerformed(evt);
            }
        });
        jPanel1.add(jMatTxt);

        jAvgTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAvgTxtActionPerformed(evt);
            }
        });
        jPanel1.add(jAvgTxt);

        jControlPnl.setLayout(new java.awt.GridLayout(2, 0));

        jInsertBtn.setText("추가하기");
        jInsertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInsertBtnActionPerformed(evt);
            }
        });
        jControlPnl.add(jInsertBtn);

        jDeleteBtn.setText("삭제하기");
        jDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteBtnActionPerformed(evt);
            }
        });
        jControlPnl.add(jDeleteBtn);

        jDataReadBtn.setText("파일읽기");
        jDataReadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDataReadBtnActionPerformed(evt);
            }
        });
        jControlPnl.add(jDataReadBtn);

        jButton4.setText("직렬화");
        jControlPnl.add(jButton4);

        jDescendingBtn.setText("내림차순");
        jDescendingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDescendingBtnActionPerformed(evt);
            }
        });
        jControlPnl.add(jDescendingBtn);

        jUpdateBtn.setText("변경하기");
        jUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateBtnActionPerformed(evt);
            }
        });
        jControlPnl.add(jUpdateBtn);

        jSearchBtn.setText("조회하기");
        jSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchBtnActionPerformed(evt);
            }
        });
        jControlPnl.add(jSearchBtn);

        jDataWriteBtn.setText("파일쓰기");
        jDataWriteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDataWriteBtnActionPerformed(evt);
            }
        });
        jControlPnl.add(jDataWriteBtn);

        jButton7.setText("역직렬화");
        jControlPnl.add(jButton7);

        jAscendingBtn.setText("오름차순");
        jControlPnl.add(jAscendingBtn);

        jResultPnl.setLayout(new java.awt.GridLayout(1, 0));

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jFirstBtn.setText("<<");
        jFirstBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFirstBtnActionPerformed(evt);
            }
        });
        jPanel3.add(jFirstBtn);

        jPrevBtn.setText("<");
        jPrevBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrevBtnActionPerformed(evt);
            }
        });
        jPanel3.add(jPrevBtn);

        jNextBtn.setText(">");
        jNextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNextBtnActionPerformed(evt);
            }
        });
        jPanel3.add(jNextBtn);

        jLastBtn.setText(">>");
        jLastBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLastBtnActionPerformed(evt);
            }
        });
        jPanel3.add(jLastBtn);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jControlPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jResultPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jControlPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jResultPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNameTxtActionPerformed

    private void jKorTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKorTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jKorTxtActionPerformed

    private void jEngTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEngTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEngTxtActionPerformed

    private void jMatTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMatTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMatTxtActionPerformed

    private void jAvgTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAvgTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAvgTxtActionPerformed

    ArrayList<Student> totalList = new ArrayList<Student>();
    ArrayList<Student> showList = totalList;
    ArrayList<Student> Search = new ArrayList<Student>();
    int[] descendingList = new int[totalList.size()];
    Student clieck;
    int page = 0;
    int countPage = 3;
    
    private void sortRank(){
        int count =0;
        for(int i = 0; i<totalList.size(); i++){
            for(int j = 0; j<totalList.size(); j++){
                if(i==j)
                    continue;
                if(totalList.get(i).avg < totalList.get(j).avg){
                    descendingList[count]+=1;
                }                    
            }
            count++;
        }
        System.out.println(descendingList);
    }

    public void showList(){
        this.jResultPnl.removeAll();
        int from = page * countPage; 
        int to = (page+1) * countPage;
        if (to>=showList.size())
            to = showList.size();
        for(int i = from ; i<to; i++){
            
            Student student = showList.get(i);
            JButton obj = new Button(student);
            obj.addActionListener(new java.awt.event.ActionListener(){
                @Override
                public void actionPerformed(ActionEvent e) {
                    Button button = (Button)e.getSource();
                    clieck = button.getStudent();
                    jNameTxt.setText(clieck.getName());
                    jKorTxt.setText(""+clieck.getKor());
                    jEngTxt.setText(""+clieck.getEng());
                    jMatTxt.setText(""+clieck.getMat());
                }
            });
            this.jResultPnl.add(obj);
        }
        this.pack();
        clieck = null;
    }
    
    private void jInsertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsertBtnActionPerformed
        Student student = new Student(
            this.jNameTxt.getText()
       +" "+this.jKorTxt.getText()
       +" "+this.jEngTxt.getText()
       +" "+this.jMatTxt.getText()
                );
        totalList.add(student);
        showList();
    }//GEN-LAST:event_jInsertBtnActionPerformed

    private void jUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateBtnActionPerformed
        if (clieck == null){
            JOptionPane aa=new JOptionPane();
            aa.showMessageDialog(null, "변경 학생 미지정");
            return;
        } 
        clieck.setName(this.jNameTxt.getText());
        clieck.setKor(Integer.parseInt(this.jKorTxt.getText()));
        clieck.setEng(Integer.parseInt(this.jEngTxt.getText()));
        clieck.setMat(Integer.parseInt(this.jMatTxt.getText()));
        showList();
        this.pack();
    }//GEN-LAST:event_jUpdateBtnActionPerformed

    private void jDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteBtnActionPerformed
        this.totalList.remove(clieck);
        showList();
        this.pack();
    }//GEN-LAST:event_jDeleteBtnActionPerformed

    
    
    private void jSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchBtnActionPerformed
        Student cmp = new Student(
                this.jNameTxt.getText()
            +" "+this.jKorTxt.getText()
            +" "+this.jEngTxt.getText()
            +" "+this.jMatTxt.getText()
        );
        Search.clear();
        for (Student student : totalList){
            if (student.compare(cmp))
                Search.add(student);
        }
        showList = Search;
        showList();
        this.pack();
    }//GEN-LAST:event_jSearchBtnActionPerformed

    private void jDataReadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDataReadBtnActionPerformed
        
    }//GEN-LAST:event_jDataReadBtnActionPerformed

    private void jDataWriteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDataWriteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDataWriteBtnActionPerformed

    private void jFirstBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFirstBtnActionPerformed
        page = 0;
        showList();
    }//GEN-LAST:event_jFirstBtnActionPerformed

    private void jPrevBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPrevBtnActionPerformed
        page--;
        if(page<0)
            page=0;
        showList();
    }//GEN-LAST:event_jPrevBtnActionPerformed

    private void jNextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNextBtnActionPerformed
        page++;
        if(showList.size()/countPage < countPage)
            page=0;
        showList();
    }//GEN-LAST:event_jNextBtnActionPerformed
    private void jLastBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLastBtnActionPerformed
        page = showList.size()/countPage;
        showList();
    }//GEN-LAST:event_jLastBtnActionPerformed

    private void jDescendingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDescendingBtnActionPerformed
        sortRank();
    }//GEN-LAST:event_jDescendingBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoreMgr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoreMgr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoreMgr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoreMgr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScoreMgr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAscendingBtn;
    private javax.swing.JLabel jAvg;
    private javax.swing.JTextField jAvgTxt;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jControlPnl;
    private javax.swing.JButton jDataReadBtn;
    private javax.swing.JButton jDataWriteBtn;
    private javax.swing.JButton jDeleteBtn;
    private javax.swing.JButton jDescendingBtn;
    private javax.swing.JLabel jEng;
    private javax.swing.JTextField jEngTxt;
    private javax.swing.JButton jFirstBtn;
    private javax.swing.JButton jInsertBtn;
    private javax.swing.JLabel jKor;
    private javax.swing.JTextField jKorTxt;
    private javax.swing.JButton jLastBtn;
    private javax.swing.JLabel jMat;
    private javax.swing.JTextField jMatTxt;
    private javax.swing.JLabel jName;
    private javax.swing.JTextField jNameTxt;
    private javax.swing.JButton jNextBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jPrevBtn;
    private javax.swing.JPanel jResultPnl;
    private javax.swing.JButton jSearchBtn;
    private javax.swing.JButton jUpdateBtn;
    // End of variables declaration//GEN-END:variables
}
