/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package test3;

import java.util.ArrayList;

/**
 *
 * @author gusal
 */
public class Score extends javax.swing.JFrame {

    /**
     * Creates new form Score
     */
    public Score() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jNameTxt = new javax.swing.JTextField();
        jKorTxt = new javax.swing.JTextField();
        jEngTxt = new javax.swing.JTextField();
        jMatTxt = new javax.swing.JTextField();
        jAvgTxt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jInsertBtn = new javax.swing.JButton();
        jDeleteBtn = new javax.swing.JButton();
        jDataReadBtn = new javax.swing.JButton();
        jUpdateBtn = new javax.swing.JButton();
        jSearchBtn = new javax.swing.JButton();
        jDataWriteBtn = new javax.swing.JButton();
        jResultPnl = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jFirstBtn = new javax.swing.JButton();
        jPrevBtn = new javax.swing.JButton();
        jNextBtn = new javax.swing.JButton();
        jLastBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        jLabel1.setText("이름");
        jPanel1.add(jLabel1);

        jLabel2.setText("국어");
        jPanel1.add(jLabel2);

        jLabel3.setText("영어");
        jPanel1.add(jLabel3);

        jLabel4.setText("수학");
        jPanel1.add(jLabel4);

        jLabel5.setText("평균");
        jPanel1.add(jLabel5);

        jNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNameTxtActionPerformed(evt);
            }
        });
        jPanel1.add(jNameTxt);

        jKorTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKorTxtActionPerformed(evt);
            }
        });
        jPanel1.add(jKorTxt);

        jEngTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEngTxtActionPerformed(evt);
            }
        });
        jPanel1.add(jEngTxt);

        jMatTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMatTxtActionPerformed(evt);
            }
        });
        jPanel1.add(jMatTxt);

        jAvgTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAvgTxtActionPerformed(evt);
            }
        });
        jPanel1.add(jAvgTxt);

        jPanel2.setLayout(new java.awt.GridLayout(2, 0));

        jInsertBtn.setText("추가하기");
        jInsertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInsertBtnActionPerformed(evt);
            }
        });
        jPanel2.add(jInsertBtn);

        jDeleteBtn.setText("삭제하기");
        jDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteBtnActionPerformed(evt);
            }
        });
        jPanel2.add(jDeleteBtn);

        jDataReadBtn.setText("파일읽기");
        jDataReadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDataReadBtnActionPerformed(evt);
            }
        });
        jPanel2.add(jDataReadBtn);

        jUpdateBtn.setText("변경하기");
        jUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateBtnActionPerformed(evt);
            }
        });
        jPanel2.add(jUpdateBtn);

        jSearchBtn.setText("조회하기");
        jSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchBtnActionPerformed(evt);
            }
        });
        jPanel2.add(jSearchBtn);

        jDataWriteBtn.setText("파일쓰기");
        jDataWriteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDataWriteBtnActionPerformed(evt);
            }
        });
        jPanel2.add(jDataWriteBtn);

        jResultPnl.setLayout(new java.awt.GridLayout());

        jPanel4.setLayout(new java.awt.GridLayout());

        jFirstBtn.setText("<<");
        jFirstBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFirstBtnActionPerformed(evt);
            }
        });
        jPanel4.add(jFirstBtn);

        jPrevBtn.setText("<");
        jPrevBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrevBtnActionPerformed(evt);
            }
        });
        jPanel4.add(jPrevBtn);

        jNextBtn.setText(">");
        jNextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNextBtnActionPerformed(evt);
            }
        });
        jPanel4.add(jNextBtn);

        jLastBtn.setText(">>");
        jLastBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLastBtnActionPerformed(evt);
            }
        });
        jPanel4.add(jLastBtn);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jResultPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jResultPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNameTxtActionPerformed
        
    }//GEN-LAST:event_jNameTxtActionPerformed

    private void jKorTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKorTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jKorTxtActionPerformed

    private void jEngTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEngTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEngTxtActionPerformed

    private void jMatTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMatTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMatTxtActionPerformed

    private void jAvgTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAvgTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAvgTxtActionPerformed

    ArrayList<Student> totalList = new ArrayList<Student>();
    ArrayList<Student> showList = totalList;
    private void showList(){
        this.jResultPnl.removeAll();
        for (int i = 0; i<totalList.size(); i+=3){
            Student student = showList.get(i);
        }
    }
    
    private void jInsertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsertBtnActionPerformed
        
    }//GEN-LAST:event_jInsertBtnActionPerformed

    private void jDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDeleteBtnActionPerformed

    private void jDataReadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDataReadBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDataReadBtnActionPerformed

    private void jUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUpdateBtnActionPerformed

    private void jSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSearchBtnActionPerformed

    private void jDataWriteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDataWriteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDataWriteBtnActionPerformed

    private void jFirstBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFirstBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFirstBtnActionPerformed

    private void jPrevBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPrevBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPrevBtnActionPerformed

    private void jNextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNextBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNextBtnActionPerformed

    private void jLastBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLastBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLastBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Score.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Score.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Score.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Score.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Score().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAvgTxt;
    private javax.swing.JButton jDataReadBtn;
    private javax.swing.JButton jDataWriteBtn;
    private javax.swing.JButton jDeleteBtn;
    private javax.swing.JTextField jEngTxt;
    private javax.swing.JButton jFirstBtn;
    private javax.swing.JButton jInsertBtn;
    private javax.swing.JTextField jKorTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jLastBtn;
    private javax.swing.JTextField jMatTxt;
    private javax.swing.JTextField jNameTxt;
    private javax.swing.JButton jNextBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jPrevBtn;
    private javax.swing.JPanel jResultPnl;
    private javax.swing.JButton jSearchBtn;
    private javax.swing.JButton jUpdateBtn;
    // End of variables declaration//GEN-END:variables
}
